### ISSUE TITLE
CAD Crash on Thread Lockup to POSTGRES

### ISSUE THREAD

**Issue by dexslab** [SnailyCAD/snaily-cadv4#1093]
### What version of Node.js are you using?

17

### What version of npm are you using?

yarn 1.22.18

### What operating system are you using?

Linux

### What version of SnailyCAD are you currently using?

1.24.0

### Describe the Bug

```[1] Error occurred during query execution:
[1] ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E40P01), message: "deadlock detected", detail: Some("Process 21254 waits for ShareLock on transaction 328652; blocked by process 21256.\nProcess 21256 waits for ShareLock on transaction 328650; blocked by process 21254."), hint: Some("See server log for query details."), position: None, where_: Some("while rechecking updated tuple (0,5) in relation \"Officer\""), schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("deadlock.c"), line: Some(1148), routine: Some("DeadLockReport") }) }) })
[1]     at RequestHandler.handleRequestError (/home/container/node_modules/@prisma/client/runtime/index.js:29913:13)
[1]     at RequestHandler.request (/home/container/node_modules/@prisma/client/runtime/index.js:29892:12)
[1]     at async PrismaClient._request (/home/container/node_modules/@prisma/client/runtime/index.js:30864:16)
[1]     at async Promise.all (index 0)
[1]     at async setInactiveUnitsOffDuty (/home/container/packages/api/src/lib/leo/setInactiveUnitsOffDuty.ts:6:3)
[1] yarn workspace @snailycad/api generate && yarn workspace @snailycad/api start exited with code 1```

### Expected Behavior

Shouldnt crash while performing queries

### To Reproduce

Cannot reproduce without active server and a lot of officers on duty

**Comment by pp2amd6** [comment]
@dexslab 
- docker installation or standalone?
- provide full version of node, run `node -v` in console
- provide full version of npm not yarn, run `npm -v` in console
- provide OS full name, run `uname -a` in console
- provide CAD full version
![image](https://user-images.githubusercontent.com/4976837/189869486-70becf83-cfc1-476e-9b69-1af0762ed16f.png)

**Comment by dexslab** [comment]
Casper is already aware of this issue I explained it to him via DM and this happens no matter what version of CAD it's on. This was just for documentation purposes so he has a direct copy of the error to work with.

**Comment by Dev-CasperTheGhost** [comment]
Yeah, I’m aware of the issue, I now will be able to hopefully debug the issue with the error

**Comment by Dev-CasperTheGhost** [comment]
I'm 70% certain this issue is fixed now, therefore I'm closing it. However if it does popup again, feel free to let me know or reopen this issue!
