### ISSUE TITLE
CAD Disconnects from API and wont go back up randomly

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/snaily-cadv4#1234]
### What version of Node.js are you using?

Latest

### What version of npm are you using?

Latest

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

v1.32.0 e7d1382

### Describe the Bug

```
[0] upstream image response failed for https://api.enemyofthestaterp.com/static/units/cl2jkvoqd181261mwtmhmtk91le.png 404
[1] DiscordAPIError[50035]: Invalid Form Body
[1] embeds[0].fields[1].value[BASE_TYPE_REQUIRED]: This field is required
[1]     at SequentialHandler.runRequest (C:\nginx\html\snaily-cadv4\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:497:11)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at async SequentialHandler.queueRequest (C:\nginx\html\snaily-cadv4\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:198:11)
[1]     at async REST.request (C:\nginx\html\snaily-cadv4\node_modules\@discordjs\rest\src\lib\REST.ts:343:20)
[1] yarn workspace @snailycad/api generate && yarn workspace @snailycad/api start exited with code 1
```

### Expected Behavior

CAD randomly shuts down at times and if I look at the console I see the above

**Comment by Dev-CasperTheGhost** [comment]
Has this happened multiple times before, Or only this one time?

**Comment by Dev-CasperTheGhost** [comment]
Please see previous comment @ViolentMinds :)

**Comment by ViolentMinds** [comment]
> Please see previous comment @ViolentMinds :)

Strangely it happened only 3 times. I don't know if its maybe if someone tries to upload an image for their character? I'm just guessing I have no idea because suddenly people start telling me CAD is down for some reason lol. It hasn't done it in a while. Very strange? We can close this for now maybe? I'm not sure. What do you think.

**Comment by Dev-CasperTheGhost** [comment]
tbh, I don't know where it comes from either. The error message doesn't list a cause deep enough for me to debug :/. If it happens again let me know ASAP (via Discord)
