### ISSUE TITLE
URGENT: Updated CAD and now it won't start up

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1826]
### What version of Node.js are you using?

--

### What operating system are you using?

Windows Server 2019

### What version of SnailyCAD are you currently using?

6c33a76

### Describe the Bug

Was trying to update the CAD and its not working anymore when I try to start. Using CAD Manager.

```
Manager API Started — Running on port 30789
Requirement NodeJS Passed
Requirement GIT Passed
Requirement pnpm Passed
Requirement Tests Complete — Checking Versions
Manager up to date!
Remote Server Running @ [::]:5002
CAD Version up to date!
✅ copied .env — client
✅ copied .env — api

• Packages in scope: @snailycad/client
• Running build in 1 packages
• Remote caching disabled

@snailycad/client:copy-env: cache bypass, force executing 696ae911acfde77b

@snailycad/config:build: cache hit, replaying logs 79c175eb0f621f62
@snailycad/config:build: 
@snailycad/config:build: > @snailycad/config@1.73.2 build C:\nginx\html\snaily-cadv4\packages\config
@snailycad/config:build: > pnpm tsup
@snailycad/config:build: 

@snailycad/permissions:build: cache hit, replaying logs ee4b33b913c7c6cb
@snailycad/permissions:build: 
@snailycad/permissions:build: > @snailycad/permissions@1.73.2 build C:\nginx\html\snaily-cadv4\packages\permissions
@snailycad/permissions:build: > pnpm tsup
@snailycad/permissions:build: 

@snailycad/types:build: cache hit, replaying logs eb0d041a4eca1904
@snailycad/types:build: 
@snailycad/types:build: > @snailycad/types@1.73.2 build C:\nginx\html\snaily-cadv4\packages\types
@snailycad/types:build: > pnpm --filter "@snailycad/api" generate && pnpm tsup
@snailycad/types:build: 
@snailycad/types:build: 
@snailycad/types:build: > @snailycad/api@1.73.2 generate C:\nginx\html\snaily-cadv4\apps\api
@snailycad/types:build: > pnpm prisma generate
@snailycad/types:build: 
@snailycad/types:build: Environment variables loaded from .env
@snailycad/types:build: Prisma schema loaded from prisma\schema.prisma
@snailycad/types:build: 
@snailycad/types:build: ✔ Generated Prisma Client (v5.4.0) to .\..\..\node_modules\.pnpm\@prisma+client@5.4.0_prisma@5.4.0\node_modules\@prisma\client in 2.60s
@snailycad/types:build: 
@snailycad/types:build: ✔ Generated prisma-generator-redundant-types to .\..\..\packages\types\src\prisma in 1.49s
@snailycad/types:build: 
@snailycad/types:build: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
@snailycad/types:build: ```
@snailycad/types:build: import { PrismaClient } from '@prisma/client'
@snailycad/types:build: const prisma = new PrismaClient()
@snailycad/types:build: ```
@snailycad/types:build: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
@snailycad/types:build: ```
@snailycad/types:build: import { PrismaClient } from '@prisma/client/edge'
@snailycad/types:build: const prisma = new PrismaClient()
@snailycad/types:build: ```
@snailycad/types:build: 
@snailycad/types:build: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
@snailycad/types:build: 

@snailycad/audit-logger:build: cache miss, executing 40177d7d7c2f94ff

@snailycad/utils:build: cache hit, replaying logs 342279631a7ef6b0
@snailycad/utils:build: 
@snailycad/utils:build: > @snailycad/utils@1.73.2 build C:\nginx\html\snaily-cadv4\packages\utils
@snailycad/utils:build: > pnpm tsup
@snailycad/utils:build: 

@snailycad/schemas:build: cache hit, replaying logs 170b631b630bc3e4
@snailycad/schemas:build: 
@snailycad/schemas:build: > @snailycad/schemas@1.73.2 build C:\nginx\html\snaily-cadv4\packages\schemas
@snailycad/schemas:build: > pnpm tsup
@snailycad/schemas:build: 

@snailycad/ui:build: cache hit, replaying logs 44d43b7452cb63fb
@snailycad/ui:build: 
@snailycad/ui:build: > @snailycad/ui@1.73.2 build C:\nginx\html\snaily-cadv4\packages\ui
@snailycad/ui:build: > pnpm tsup
@snailycad/ui:build: 

@snailycad/client:copy-env: 
@snailycad/client:copy-env: > @snailycad/client@1.73.2 copy-env C:\nginx\html\snaily-cadv4\apps\client
@snailycad/client:copy-env: > node ../../scripts/copy-env.mjs --client
@snailycad/client:copy-env: 

@snailycad/audit-logger:build: 
@snailycad/audit-logger:build: > @snailycad/audit-logger@1.73.2 build C:\nginx\html\snaily-cadv4\packages\audit-logger
@snailycad/audit-logger:build: > npx rimraf ./dist && pnpm --filter "@snailycad/api" generate && pnpm tsup
@snailycad/audit-logger:build: 

@snailycad/client:copy-env: ✅ copied .env — client

@snailycad/audit-logger:build: 
@snailycad/audit-logger:build: > @snailycad/api@1.73.2 generate C:\nginx\html\snaily-cadv4\apps\api
@snailycad/audit-logger:build: > pnpm prisma generate
@snailycad/audit-logger:build: 

@snailycad/audit-logger:build: Environment variables loaded from .env

@snailycad/audit-logger:build: Prisma schema loaded from prisma\schema.prisma

@snailycad/audit-logger:build: 
@snailycad/audit-logger:build: ✔ Generated Prisma Client (v5.4.0) to .\..\..\node_modules\.pnpm\@prisma+client@5.4.0_prisma@5.4.0\node_modules\@prisma\client in 2.81s
@snailycad/audit-logger:build: 
@snailycad/audit-logger:build: ✔ Generated prisma-generator-redundant-types to .\..\..\packages\types\src\prisma in 1.67s
@snailycad/audit-logger:build: 
@snailycad/audit-logger:build: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
@snailycad/audit-logger:build: ```
@snailycad/audit-logger:build: import { PrismaClient } from '@prisma/client'
@snailycad/audit-logger:build: const prisma = new PrismaClient()
@snailycad/audit-logger:build: ```
@snailycad/audit-logger:build: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
@snailycad/audit-logger:build: ```
@snailycad/audit-logger:build: import { PrismaClient } from '@prisma/client/edge'
@snailycad/audit-logger:build: const prisma = new PrismaClient()
@snailycad/audit-logger:build: ```
@snailycad/audit-logger:build: 
@snailycad/audit-logger:build: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
@snailycad/audit-logger:build: 

@snailycad/audit-logger:build: src/server.ts(31,9): error TS2578: Unused '@ts-expect-error' directive.
@snailycad/audit-logger:build: 

@snailycad/audit-logger:build: [31mError: error occured in dts build
@snailycad/audit-logger:build:     at Worker.<anonymous> (C:\nginx\html\snaily-cadv4\node_modules\.pnpm\tsup@6.6.2_postcss@8.4.31_typescript@5.2.2\node_modules\tsup\dist\index.js:2276:26)
@snailycad/audit-logger:build:     at Worker.emit (node:events:513:28)
@snailycad/audit-logger:build:     at MessagePort.<anonymous> (node:internal/worker:243:53)
@snailycad/audit-logger:build:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
@snailycad/audit-logger:build:     at exports.emitMessage (node:internal/per_context/messageport:23:28)[39m

@snailycad/audit-logger:build: [31mDTS[39m [31mBuild error[39m
@snailycad/audit-logger:build: [31mRollupError: Failed to compile. Check the logs above.
@snailycad/audit-logger:build:     at error (C:\nginx\html\snaily-cadv4\node_modules\.pnpm\rollup@3.28.1\node_modules\rollup\dist\shared\rollup.js:353:30)
@snailycad/audit-logger:build:     at Object.error (C:\nginx\html\snaily-cadv4\node_modules\.pnpm\rollup@3.28.1\node_modules\rollup\dist\shared\rollup.js:1720:20)
@snailycad/audit-logger:build:     at Object.error (C:\nginx\html\snaily-cadv4\node_modules\.pnpm\rollup@3.28.1\node_modules\rollup\dist\shared\rollup.js:25543:42)
@snailycad/audit-logger:build:     at Object.transform (C:\nginx\html\snaily-cadv4\node_modules\.pnpm\tsup@6.6.2_postcss@8.4.31_typescript@5.2.2\node_modules\tsup\dist\rollup.js:7381:20)
@snailycad/audit-logger:build:     at C:\nginx\html\snaily-cadv4\node_modules\.pnpm\rollup@3.28.1\node_modules\rollup\dist\shared\rollup.js:1913:40[39m

@snailycad/audit-logger:build:  ELIFECYCLE  Command failed with exit code 1.

@snailycad/audit-logger:build: ERROR: command finished with error: command (C:\nginx\html\snaily-cadv4\packages\audit-logger) pnpm run build exited (1)
@snailycad/audit-logger#build: command (C:\nginx\html\snaily-cadv4\packages\audit-logger) pnpm run build exited (1)
 ERROR  run failed: command  exited (1)


 Tasks:    7 successful, 8 total
Cached:    6 cached, 8 total
  Time:    1m52.241s 
Failed:    @snailycad/audit-logger#build


CAD Process exited with code 1
Launching URL: C:\Users\Administrator\AppData\Local\Programs\SnailyCAD Manager\resources\logs\app.log

```

### Expected Behavior

To start normally.

**Comment by casperiv0** [comment]
This is now fixed, please update
