### ISSUE TITLE
Cannot Prune Users / Features

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/snaily-cadv4#1904]
### What version of Node.js are you using?

Latest

### What operating system are you using?

Windows Server 2022

### What version of SnailyCAD are you currently using?

v1.79.1 66e1af8

### Describe the Bug

Pruning will not work. We've got 4100 users and every time I try to prune it simply won't prune any. I will usually try 6 months inactive range. Can we manually trim users in the DB? Is this some issue with foreign key checks or what? It just gives a network error. I'm assuming maybe because there are so many that its trying to prune at once that it times out or something? Its really irritating.

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/5ae36da0-284e-4ae0-a813-ce88363fbfc9)

Additionally, I wanted to suggest ability to Citizens maybe if they haven't been used in months?
### Expected Behavior

To be able to prune users.

**Comment by Infiniti-Development** [comment]
If you can give an error log on your windwows server that will help. @Legacy-TacticalGamingInteractive

**Comment by Legacy-TacticalGamingInteractive** [comment]
> If you can give an error log on your windows server that will help. @Legacy-TacticalGamingInteractive

I'm not seeing any related event logs. Perhaps you need log from console of SnailyCAD Manager?

**Comment by Infiniti-Development** [comment]
No indeed peds you need to delete in your database it self
But normal civ's you should be able to delete from the CAD.

**Comment by Legacy-TacticalGamingInteractive** [comment]
How can I delete peoples pets without knowing which ones need to be pruned though. Unfortunately its making pruning impossible unless I go into the database and wipe everyones pets including the ones that are still being used by active people. That presents a rather large issue.

I was also not able to delete citizens that have pets one at a time in CAD either. It will not work unless their pet is manually deleted one at a time. Which you can see is impossible with this many users. I would be there for a year lol.

**Comment by Infiniti-Development** [comment]
@Legacy-TacticalGamingInteractive Hello, We are looking in to this problem.

**Comment by Legacy-TacticalGamingInteractive** [comment]
> @Legacy-TacticalGamingInteractive Hello, We are looking in to this problem.

![image](https://github.com/SnailyCAD/snaily-cadv4/assets/25211271/97d2c2b0-0977-48e5-9891-3a45710db3dd)


Sounds good. PS you can also replicate it when attempting to individually delete any Citizen with a pet.
Since we have no way to delete someones pet as an admin theres nothing we can do about it haha.

**Comment by WhitigolProd** [comment]
I'm unable to reproduce this. Does this only occur when pruning users? I attempted to delete a citizen that had a pet, and it deleted just fine, no foreign key constraint.

cc @Legacy-TacticalGamingInteractive

**Comment by MarshyMelloow** [comment]
I am able to reproduce this @WhitigolProd on v1.79.1 47faaa4
  


```

Prismaclientknownrequesterror ( Invalid `Prisma.User.Delete()` Invocation: Foreign Key Constraint Failed On The Field: `PetMedicalRecord_petId_fkey (Index)`)

An unexpected error occurred
```

SnailyCAD Console Log:

`[1]
[1] SnailyCADv4 is running with version 1.79.1 - 47faaa4. Node version: 18.17.1
[1] prisma:error
[1] Invalid `prisma.user.delete()` invocation:
[1]
[1]
[1] Foreign key constraint failed on the field: `PetMedicalRecord_petId_fkey (index)`
[1] [2024-02-11T21:09:52.693] [ERROR] [SnailyCAD] - {
[1]   method: 'DELETE',
[1]   url: '/v1/admin/manage/users/cll7nxaom0001fb1eexkaqpb4',
[1]   route: '/v1/admin/manage/users/:id',
[1]   headers: {
[1]     connection: 'upgrade',
[1]     host: 'demo-api.snailycad.org',
[1]     'x-forwarded-for': '92.109.193.29',
[1]     'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "Opera GX";v="106"',
[1]     accept: 'application/json, text/plain, */*',
[1]     'sec-ch-ua-mobile': '?0',
[1]     'is-from-dispatch': 'false',
[1]     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 OPR/106.0.0.0',
[1]     session: '',
[1]     'sec-ch-ua-platform': '"Windows"',
[1]     origin: 'https://demo.snailycad.org',
[1]     'sec-fetch-site': 'same-site',
[1]     'sec-fetch-mode': 'cors',
[1]     'sec-fetch-dest': 'empty',
[1]     'accept-encoding': 'gzip, deflate, br',
[1]     'accept-language': 'nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7',
[1]     cookie: 'google-analytics_v4_Snoo__ga4=44c3d74f-b4ce-4ff0-9c92-3c19b63c8b1f; google-analytics_v4_Snoo___z_ga_audiences=44c3d74f-b4ce-4ff0-9c92-3c19b63c8b1f; _ga=GA1.1.1805509624.1707076323; sn_isDarkTheme=true; google-analytics_v4_Snoo__session_counter=7; google-analytics_v4_Snoo__engagementDuration=0; _ga_HE45R7EFY2=GS1.1.1707609371.8.1.1707609812.53.0.0; google-analytics_v4_Snoo__engagementStart=1707609979591; google-analytics_v4_Snoo__counter=19; google-analytics_v4_Snoo__let=1707609979591; snaily-cad-session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbHM3eHNhMTgwMDFuaTNrYzZ0czJzMXpoIiwiaWF0IjoxNzA3Njg1NzU0LCJleHAiOjE3MDc2ODkzNTR9.F9w3YXbon_V7YRSSC91mRNc89lUi8g8Ue7FKE-Ni3bw; snaily-cad-refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJ2ZzhpOWl2YjRjZnZ2bmt2MW55azM2dzUiLCJpYXQiOjE3MDc2ODU3NTMsImV4cCI6MTcwODI5MDU1M30.ZaCFfZtCiK_SQnan249pH6THtquMdkW5xpKH8PZ3NWY'
[1]   },
[1]   body: {},
[1]   query: {},
[1]   params: {},
[1]   reqId: '96b7ec2a594a47bb90e880a3f4c801c5',
[1]   time: 2024-02-11T21:09:52.693Z,
[1]   duration: 1594,
[1]   error: {
[1]     name: 'PrismaClientKnownRequestError',
[1]     message: '\n' +
[1]       'Invalid `prisma.user.delete()` invocation:\n' +
[1]       '\n' +
[1]       '\n' +
[1]       'Foreign key constraint failed on the field: `PetMedicalRecord_petId_fkey (index)`',
[1]     status: 500,
[1]     errors: []
[1]   },
[1]   catch: true
[1] }
[1] [2024-02-11T21:09:52.698] [ERROR] [SnailyCAD] - {
[1]   method: 'DELETE',
[1]   url: '/v1/admin/manage/users/cll7nxaom0001fb1eexkaqpb4',
[1]   route: '/v1/admin/manage/users/:id',
[1]   headers: {
[1]     connection: 'upgrade',
[1]     host: 'demo-api.snailycad.org',
[1]     'x-forwarded-for': '92.109.193.29',
[1]     'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "Opera GX";v="106"',
[1]     accept: 'application/json, text/plain, */*',
[1]     'sec-ch-ua-mobile': '?0',
[1]     'is-from-dispatch': 'false',
[1]     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 OPR/106.0.0.0',
[1]     session: '',
[1]     'sec-ch-ua-platform': '"Windows"',
[1]     origin: 'https://demo.snailycad.org',
[1]     'sec-fetch-site': 'same-site',
[1]     'sec-fetch-mode': 'cors',
[1]     'sec-fetch-dest': 'empty',
[1]     'accept-encoding': 'gzip, deflate, br',
[1]     'accept-language': 'nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7',
[1]     cookie: 'google-analytics_v4_Snoo__ga4=44c3d74f-b4ce-4ff0-9c92-3c19b63c8b1f; google-analytics_v4_Snoo___z_ga_audiences=44c3d74f-b4ce-4ff0-9c92-3c19b63c8b1f; _ga=GA1.1.1805509624.1707076323; sn_isDarkTheme=true; google-analytics_v4_Snoo__session_counter=7; google-analytics_v4_Snoo__engagementDuration=0; _ga_HE45R7EFY2=GS1.1.1707609371.8.1.1707609812.53.0.0; google-analytics_v4_Snoo__engagementStart=1707609979591; google-analytics_v4_Snoo__counter=19; google-analytics_v4_Snoo__let=1707609979591; snaily-cad-session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbHM3eHNhMTgwMDFuaTNrYzZ0czJzMXpoIiwiaWF0IjoxNzA3Njg1NzU0LCJleHAiOjE3MDc2ODkzNTR9.F9w3YXbon_V7YRSSC91mRNc89lUi8g8Ue7FKE-Ni3bw; snaily-cad-refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJ2ZzhpOWl2YjRjZnZ2bmt2MW55azM2dzUiLCJpYXQiOjE3MDc2ODU3NTMsImV4cCI6MTcwODI5MDU1M30.ZaCFfZtCiK_SQnan249pH6THtquMdkW5xpKH8PZ3NWY'
[1]   },
[1]   body: {},
[1]   query: {},
[1]   params: {},
[1]   reqId: '96b7ec2a594a47bb90e880a3f4c801c5',
[1]   time: 2024-02-11T21:09:52.698Z,
[1]   duration: 1599,
[1]   event: 'request.end',
[1]   status: 500,
[1]   status_code: '500',
[1]   state: 'KO',
[1]   error_name: 'PrismaClientKnownRequestError',
[1]   error_message: '\n' +
[1]     'Invalid `prisma.user.delete()` invocation:\n' +
[1]     '\n' +
[1]     '\n' +
[1]     'Foreign key constraint failed on the field: `PetMedicalRecord_petId_fkey (index)`',
[1]   error_stack: 'PrismaClientKnownRequestError: \n' +
[1]     'Invalid `prisma.user.delete()` invocation:\n' +
[1]     '\n' +
[1]     '\n' +
[1]     'Foreign key constraint failed on the field: `PetMedicalRecord_petId_fkey (index)`\n' +
[1]     '    at ni.handleRequestError (/root/snaily-cadv4/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:124:6817)\n' +
[1]     '    at ni.handleAndLogRequestError (/root/snaily-cadv4/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:124:6206)\n' +
[1]     '    at ni.request (/root/snaily-cadv4/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:124:5926)\n' +
[1]     '    at async l (/root/snaily-cadv4/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:129:10023)'
[1] }
`

**Comment by WhitigolProd** [comment]
> I am able to reproduce this @WhitigolProd on v1.79.1

Were you able to reproduce by attempting to directly delete a user, or when pruning the user(s)?

cc @MarshyMelloow

**Comment by MarshyMelloow** [comment]
I got this error when directly deleting a user.

**Comment by Legacy-TacticalGamingInteractive** [comment]
It happens when directly deleting a user for me. Or pruning. Either way the action is the same its blocked by the foreign key constraint.

**Comment by WhitigolProd** [comment]
Hmm. I'm still unable to reproduce. It may be because I'm on a fresh database? I'm not too sure to be honest. I will look into a couple different possible solutions to see what I can figure out.

Thanks again for reporting this!

**Comment by WhitigolProd** [comment]
> Additionally, I wanted to suggest ability to Citizens maybe if they haven't been used in months?

By this, you mean the ability to prune citizens?

**Comment by WhitigolProd** [comment]
Gotcha, yeah I don't think that'd be too hard to implement, I'll see what I can do after I track down this foreign key constraint issue!

**Comment by WhitigolProd** [comment]
Fixed in https://github.com/SnailyCAD/snaily-cadv4/commit/301f6ad

Please update your instance, @Legacy-TacticalGamingInteractive and let me know if you have any further issues!
