### ISSUE TITLE
Editing Vehicles Broken

### ISSUE THREAD

**Issue by nick-perry14** [SnailyCAD/snaily-cadv4#404]
### What version of Node.js are you using?

16.14.0

### What version of npm are you using?

8.3.1

### What operating system are you using?

Ubuntu Server

### Describe the Bug

When attempting to edit a vehicle in the admin panel, a client error occurs.

```
main-34e291e942f4a5a3.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at f (1207-8f955dab526a9949.js:1:23552)
    at X (1207-8f955dab526a9949.js:1:8497)
    at ro (framework-d124cb1da80cd7e9.js:1:59433)
    at jo (framework-d124cb1da80cd7e9.js:1:69000)
    at Hu (framework-d124cb1da80cd7e9.js:1:112882)
    at Pi (framework-d124cb1da80cd7e9.js:1:99065)
    at xi (framework-d124cb1da80cd7e9.js:1:98993)
    at _i (framework-d124cb1da80cd7e9.js:1:98856)
    at vi (framework-d124cb1da80cd7e9.js:1:95822)
    at framework-d124cb1da80cd7e9.js:1:45201
Pe @ main-34e291e942f4a5a3.js:1
main-34e291e942f4a5a3.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Pe @ main-34e291e942f4a5a3.js:1
```
![Screenshot from 2022-02-15 16-45-59](https://user-images.githubusercontent.com/6935777/154154730-c3725626-4254-413c-a09f-2290cccdb7d4.png)

### Expected Behavior

It should open up an edit window

EDIT: Deleting Vehicles is broken as well
Edit: Editing Weapons also broken

**Comment by Dev-CasperTheGhost** [comment]
Hmm, not sure what causes this. Will need t debug shortly!
