### ISSUE TITLE
Department Whitelist > Admin Accept Bug

### ISSUE THREAD

**Issue by DeputyHess** [SnailyCAD/snaily-cadv4#536]
### What version of Node.js are you using?

16.14.0

### What version of npm are you using?

8.3.1

### What operating system are you using?

Ubuntu

### Describe the Bug

When trying to accept or deny an officer in Admin -> Manage Units > Department Whitelisting it gives the following error below. This happens when trying to accept or deny the officer into the department. The below error only shows the accept request but the same happens for denys.

[1]     'sec-fetch-dest': 'empty',
[1]     'sec-fetch-mode': 'cors',
[1]     'sec-fetch-site': 'same-site'
[1]   },
[1]   body: { type: 'ACCEPT' },
[1]   query: {},
[1]   params: {},
[1]   reqId: 'c82effd3c1bd457d96b24f7436bcf230',
[1]   time: 2022-03-17T16:55:40.429Z,
[1]   duration: 21,
[1]   error: {
[1]     name: 'BAD_REQUEST',
[1]     message: 'invalidType',
[1]     status: 400,
[1]     errors: [],
[1]     stack: undefined
[1]   },
[1]   stack: 'BAD_REQUEST: invalidType\n' +
[1]     '    at ManageUnitsController.acceptOrDeclineUnit (/var/www/html/snaily-cadv4/packages/api/src/controllers/admin/manage/Units.ts:185:13)\n' +
[1]     '    at /var/www/html/snaily-cadv4/node_modules/@tsed/platform-params/src/builder/PlatformParams.ts:87:16'
accepted

### Expected Behavior

Decline or Accept the Officer with the buttons in the admin menu

### To Reproduce

make a whitelisted department and a character for it. Add into the department go into admin and try to accept or deny it.

**Comment by Dev-CasperTheGhost** [comment]
Should be fixed now! Sorry for any inconvenience.
